name: Example workflow

on: [push]

jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.6.1
        with:
          minikube version: 'v1.26.0'
          kubernetes version: 'v1.24.1'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Interact with the cluster
        run: kubectl get nodes
      - name: Create nginx pod
        run: kubectl run nginx --image nginx
      - name: Get pods
        run: kubectl get pods
      